<?php
/**
 * Created by PhpStorm.
 * User: ralph
 * Date: 07.05.17
 * Time: 20:11
 */

/**
 * Defines the JWPlayer content base path.
 */
define('JWPLAYER_CONTENT_BASE_PATH', 'https://content.jwplatform.com/');

/**
 * Defines the JWPlayer cdn base path.
 */
define('JWPLAYER_CDN_BASE_PATH', 'https://cdn.jwplatform.com/');

/**
 * Defines access to single line embeddable cloud-hosted players with no media.
 */
define('JWPLAYER_CLOUD_PLAYER_PATH', 'libraries/');

/**
 * Defines access to single line embeddable cloud-hosted players with media.
 */
define('JWPLAYER_CLOUD_PLAYER_MEDIA_PATH', 'players/');

/**
 * Defines access to individual video transcodes.
 */
define('JWPLAYER_VIDEO_PATH', 'videos/');

/**
 * Defines access to video poster images.
 */
define('JWPLAYER_THUMB_PATH', 'thumbs/');

/**
 * Defines access to adaptive bitrate streaming manifests for videos.
 */
define('JWPLAYER_MANIFEST_PATH', 'manifests/');

/**
 * Defines access to video timed text track files.
 */
define('JWPLAYER_TRACK_PATH', 'tracks/');



/**
 * Load the management API methods
 */
module_load_include('inc', 'video_embed_jwplayer', 'video_embed_jwplayer.management');

/**
 * Load the video embed handler
 */
module_load_include('inc', 'video_embed_jwplayer', 'video_embed_jwplayer.handler');


/* -----------------------------------------------------------------
 *  Hook implementations
 * ----------------------------------------------------------------- */
/**
 * Implements hook_libraries_info().
 */
function video_embed_jwplayer_libraries_info() {
  $libraries['jwplayer_api'] = array(
    'name' => 'JWPlayer Management API',
    'vendor url' => 'https://developer.jwplayer.com/jw-platform/docs/developer-guide/management-api',
    'download url' => 'http://support-static.jwplayer.com/API/php-api-kit-20151013.zip',
    'version callback' => 'video_embed_jwplayer_version_callback',
    'files' => array(
      'php' => array(
        'api.php',
      )
    ),
  );
  return $libraries;
}

function video_embed_jwplayer_version_callback() {
  return '1.4';
}

/**
 * Implements hook_menu().
 */
function video_embed_jwplayer_menu() {
  $items = array();

  $items['admin/config/media/vef/jwplayer_settings'] = array(
    'title' => 'JWPlayer Settings',
    'description' => 'JWPlayer settings for the Video Embed Field.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('video_embed_jwplayer_settings_form'),
    'access arguments' => array('administer video styles'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/* -----------------------------------------------------------------
 *  Admin settings form
 * ----------------------------------------------------------------- */

function _get_account_properties() {
  $account_properties = array(
    'default' => t('Default account property'),
  );

  // allow others to alter the account properties
  drupal_alter('video_embed_jwplayer_account_properties', $account_properties);

  return $account_properties;
}

/**
 * VEF settings page form callback.
 */
function video_embed_jwplayer_settings_form($form, &$form_state) {
  // find selected property (in Ajax call)
  $property_key = isset($form_state['values']['video_embed_jwplayer_properties']) ?
    $form_state['values']['video_embed_jwplayer_properties'] : variable_get('video_embed_jwplayer_properties', '');

//
// JWPlayer account properties$
  $jwplayer_account_properties = _get_account_properties();
  $form['video_embed_jwplayer_properties'] = array(
    '#type' => 'select',
    '#title' => t('Choose the JWPlayer Account Property.'),
    '#options' => $jwplayer_account_properties,
    '#default_value' => $property_key,
    '#description' => t('Select the JWPlayer account properties for which you want to set the credentials. Set the credentials for ALL used properties of the account.'),
    '#weight' => -1,
    '#ajax' => array(
      'event' => 'change',
      'callback' => 'ajax_select_callback',
      'wrapper' => 'property-settings',
      'method' => 'replace',
    ),
  );

  $form['property_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Configure JWPlayer @prop', array('@prop' => $jwplayer_account_properties[$property_key])),
    '#collapsible' => true,
    '#collapsed' => false,
    '#description' => t('Set the credentials for the specific JWPlayer acoount property.'),
    '#prefix' => '<div id="property-settings">',
    '#suffix' => '</div>',
    '#weight' => 10,
  );
  $form['property_settings']['video_embed_jwplayer_api_key_' . $property_key] = array(
    '#type' => 'textfield',
    '#title' => t('API key'),
    '#default_value' => variable_get('video_embed_jwplayer_api_key_' . $property_key, ''),
    '#description' => t('Set the API key of the JWPlayer account property. See JWPlayer Account->Properties->API Credentials.'),
    '#weight' => 10,
  );
  $form['property_settings']['video_embed_jwplayer_api_secret_' . $property_key] = array(
    '#type' => 'textfield',
    '#title' => t('API secret'),
    '#default_value' => variable_get('video_embed_jwplayer_api_secret_' . $property_key, ''),
    '#description' => t('Set the API secret of the JWPlayer account property. See JWPlayer Account->Properties->API Credentials.'),
    '#weight' => 20,
  );
  if (variable_get('video_embed_jwplayer_api_secret_' . $property_key, '')) {
    $form['property_settings']['video_embed_jwplayer_test'] = array(
      '#type' => 'button',
      '#value' => t('Test JWPlatform Connection'),
      '#ajax' => array(
        'callback' => '_video_embed_jwplayer_management_api_test_connection',
        'wrapper' => 'jwplayer-connect-results',
        'method' => 'append',
      ),
      '#suffix' => '<div id="jwplayer-connect-results"></div>',
      '#weight' => 30,
    );
  }

  return system_settings_form($form);
}


/**
 * AJAX callback for the select field.
 */
function ajax_select_callback($form, &$form_state) {
  return $form['property_settings'];
}

/**
 * AJAX callback to test connection with the JWPlayer Management API.
 */
function _video_embed_jwplayer_management_api_test_connection($form, &$form_state) {
  //
  // get the system status as test
  $property_key = isset($form_state['values']['video_embed_jwplayer_properties']) ?
    $form_state['values']['video_embed_jwplayer_properties'] : 'geo_blocking';

  if ($jwplayer_api = video_embed_jwplayer_get_instance($property_key)) {
    $response = $jwplayer_api->call('/accounts/show');

    if ($response['status'] == 'ok') {
      $message = t('SUCCESS! Your JWPlayer Edition is "@edition". You have @amount videos uploaded.', array(
        '@edition' => $response['account']['jwplayer_edition'],
        '@amount' => $response['account']['videos']['total'],
      ));
    }
    else {
      $message = t('Error "@code": @msg', array('@code' => $response['code'], '@msg' => $response['message']));
    }
  }
  else {
    $message = t('ERROR "Library not installed": The JWPlayer API library cannot be loaded. Check JWPLayer library installation!');
  }

  // return test message
  return $message;
}


