<?php
/**
 * Provides all functionality needed to build the Swiss1 TV portal.
 * User: ralph
 * Date: 07.05.17
 * Time: 20:02
 */

/**
 * Define the admin menu path of Swiss1 TV
 */
define('SWISS1_ADMIN_MENU_PATH', 'admin/swiss1');

/**
 * Load the Swiss1 media importer.
 */
module_load_include('inc', 'swiss1', 'swiss1.import');


/* -----------------------------------------------------------------
 *  Hook implementation
 * ----------------------------------------------------------------- */

/**
 * Implements hook_permission().
 */
function swiss1_permission() {
  return array(
    'administer swiss1 tv' => array(
      'title' => t('Administer Swiss1 TV'),
      'description' => t('Allows to administer the Swiss1 TV settings.'),
    ),
  );
}

/**
 * Defines the Swiss1 TV menu in the top node of the admin menu.
 * All administration forms of the Swiss1 TV platform are added to this menu.
 */
function swiss1_menu() {
  $items[SWISS1_ADMIN_MENU_PATH] = array(
    'title' => t('Swiss1 TV'),
    'description' => t('Swiss1 TV - «iischalte und erläbe»'),
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer swiss1 tv'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => -7,
  );

  //
  // pxlraffle admin forms
  $items[SWISS1_ADMIN_MENU_PATH . '/import'] = array(
    'title' => t('Media import'),
    'description' => t('Import the newest media files and meta data.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('swiss1_import_settings_form'),
    'access arguments' => array('administer swiss1 tv'),
    'file' => 'swiss1.admin.inc',
    'weight' => 0,
  );
  return $items;
}


/**
 * Disables all video items, which have been expired by the set catch-up rights.
 */
function swiss1_cron() {
  $last_time = variable_get('swiss1_cron_last_run', 0);

  //
  // delete all video streams with an expiration date in the past (catch-up rights)
  swiss1_delete_expired_media();

  //
  // import/update the media files and meta data
  swiss1_media_import();

  //
  // update last run variable
  variable_set('swiss1_cron_last_run', REQUEST_TIME);
}

/**
 * Allows altering a view at the very beginning of views processing, before
 * anything is done.
 **/
function swiss1_views_pre_view(&$view, &$display_id, &$args) {
  //
  // dynamically set the daily prime-time broadcasts (videostream nodes) as featured,
  // reset flag for others
  if ($view->name == 'featured' && $display_id == 'block') {
    // delete all featured content first
    _reset_featured_content();

    // feature prime-time broadcasts of today
    _set_daily_featured_content();
  }
}

function _reset_featured_content() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'videostream')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_featured', 'value', 1);
  $result = $query->execute();

  if (isset($result['node'])) {
    $nodes = node_load_multiple(array_keys($result['node']));
    foreach ($nodes as $node) {
      $node->field_featured[LANGUAGE_NONE][0]['value'] = 0;
      node_save($node);
    }
  }
}


function _set_daily_featured_content() {
  $today = strtotime('today');
  $tomorrow = strtotime('tomorrow');
  $start_date = date('Y-m-d H:i:s', $today);  // format matters for comparison to work
  $end_date = date('Y-m-d H:i:s', $tomorrow);  // format matters for comparison to work

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'videostream')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_run_type', 'value', 'primary')
    ->fieldCondition('field_featured', 'value', 0)
    ->fieldCondition('field_broadcast_date', 'value', $start_date, '>')
    ->fieldCondition('field_broadcast_date', 'value', $end_date, '<');
  $result = $query->execute();

  if (isset($result['node'])) {
    $nodes = node_load_multiple(array_keys($result['node']));
    foreach ($nodes as $node) {
      $node->field_featured[LANGUAGE_NONE][0]['value'] = 1;
      node_save($node);
    }
  }
}


/* -----------------------------------------------------------------
 *  JWPlayer API implementation
 * ----------------------------------------------------------------- */

/**
 * Implements hook hook_video_embed_jwplayer_account_properties_alter().
 */
function swiss1_video_embed_jwplayer_account_properties_alter(&$account_properties) {
  //
  // Set account properties of Swiss1 account
  unset($account_properties['default']);
  $account_properties['geo_blocking'] = t('Account property with geo-blocking');
  $account_properties['non_geo_blocking'] = t('Account property without geo-blocking');
}

/**
 * Returns the latest validity end timestamp value of all currently valid nodes
 * with the given video (media id).
 *
 * @param int $exp_timestamp
 *    The UNIX timestamp to be overridden by this function.
 * @param $media_id
 *    The media-id of the video to be expired.
 */
function swiss1_video_embed_jwplayer_expiration_timestamp_alter(&$exp_timestamp, $media_id) {
  //
  // get expiration date from the node with the given media id
  $now = date('Y-m-d H:i:s'); // format matters for comparison to work
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'videostream')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_media_id', 'value', $media_id)
    ->fieldCondition('field_run_type', 'value', array('primary', 'primary_repeat'), 'IN')
    ->fieldCondition('field_validity_period', 'value', $now, '<')
    ->fieldOrderBy('field_validity_period', 'value2', 'DESC')
    ->range(0,1);
  $result = $query->execute();

  if (isset($result['node'])) {
    $node = node_load(key($result['node']));
    if (!empty($node->field_validity_period)) {
      $date = $node->field_validity_period[LANGUAGE_NONE][0]['value2'];
      $timestamp = strtotime($date);

      // if no (valid) timestamp is set on the node, don't show video
      $exp_timestamp = $timestamp ? $timestamp : time();
    }
  }
}
